spring:
  application:
    name: productos-service
  cloud:
    aws:
      region:
        static: ${CLOUDWATCH_REGION:us-east-1}
      credentials:
        access-key: ${CLOUDWATCH_ACCESS_KEY:test}
        secret-key: ${CLOUDWATCH_SECRET_KEY:test}
      endpoint: ${CLOUDWATCH_ENDPOINT:http://localhost:4566}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/db_productos}

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

observability:
  cloudwatch:
    logs:
      endpoint: ${CLOUDWATCH_ENDPOINT:http://localhost:4566}
      region: ${CLOUDWATCH_REGION:us-east-1}
      access-key: ${CLOUDWATCH_ACCESS_KEY:test}
      secret-key: ${CLOUDWATCH_SECRET_KEY:test}
      log-group: ${CLOUDWATCH_LOG_GROUP:producto-log-group}
      log-stream-prefix: ${CLOUDWATCH_LOG_STREAM_PREFIX:productos-service}

logging:
  level:
    root: INFO
    com.product.productservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} traceId=%X{traceId:-N/A} spanId=%X{spanId:-N/A} - %msg%n"
